AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  DBEndpoint:
    Type: String
    Description: "Database endpoint"
  DBName:
    Type: String
    Description: "Database name"
  DBUsername:
    Type: String
    Description: "Username for database access"
  DBPassword:
    Type: String
    Description: "Password for database access"

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DB_HOST: !Ref DBEndpoint
        DB_PASSWORD: !Ref DBPassword
        DB_USER: !Ref DBUsername
        DB_NAME: !Ref DBName
    VpcConfig:
      SecurityGroupIds:
        - sg-057bc420
      SubnetIds:
        - subnet-00f2720e
        - subnet-17c8da29

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  GetReceivingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receiving_handler/
      Handler: handler.get
      Runtime: python3.6
      Events:
        GetReceiving:
          Type: Api
          Properties:
            Path: /receivings/{id}
            Method: get

  CreateReceivingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receiving_handler/
      Handler: handler.create
      Runtime: python3.6
      Events:
        CreateReceiving:
          Type: Api
          Properties:
            Path: /receivings
            Method: post

  GetAllReceivingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receiving_handler/
      Handler: handler.get_all
      Runtime: python3.6
      Events:
        GetAllReceiving:
          Type: Api
          Properties:
            Path: /receivings
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
